src/AssessmentEF.MVC/Models/BaseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AssessmentEF.MVC.Models
{
    public class BaseModel
    {
    }
}

src/AssessmentEF.MVC/Models/ErrorViewModel.cs
namespace AssessmentEF.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/AssessmentEF.MVC/Models/Personnel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AssessmentEF.MVC.Models
{
    public class Personnel:BaseModel
    {
        public int ID { get; set; }
        [Required]
        [Display(Name = "Adı")]
        public String Name { get; set; }
        [Required]
        [Display(Name = "Soyadı")]
        public String Surname { get; set; }
        [Required]
        [Display(Name = "Doğum Tarihi")]
        public DateTime BirthDate { get; set; }
        [Required]
        [Display(Name = "Cinsiyeti")]
        public Gender Gender { get; set; }
        public virtual Salary Salary { get; set; }
    }

    public enum Gender
    {
        [Display(Name = "Kadın")] Female = 1,
        [Display(Name = "Erkek")] Male = 2
    }
}

src/AssessmentEF.MVC/Models/Salary.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace AssessmentEF.MVC.Models
{
    public class Salary:BaseModel
    {
        public int PersonnelId { get; set; }
        [Display(Name = "Departman")]
        public Department Department { get; set; } = Department.None;
        [Display(Name = "Ücret")]
        public decimal PersonnelSalary { get; set; } = 0;      
    }
    public enum Department
    {
        None,
        Finance,
        HumanResources,
        RD,
        Accounting,
        SoftwareDevelopement,
    }
}

src/AssessmentEF.MVC/Controllers/PersonnelController.cs
using Microsoft.AspNetCore.Mvc;
using AssessmentEF.MVC.Models;
using System.Text.Json.Serialization;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;
using System.Xml;

namespace AssessmentEF.MVC.Controllers
{
    public class PersonnelController : Controller
    {
        private readonly Uri _baseAddress = new Uri("http://localhost:5271/api");
        private readonly HttpClient _client;
        private readonly JsonSerializerOptions options;

        public PersonnelController()
        {
            _client = new HttpClient();
            _client.BaseAddress= _baseAddress;
            options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            };
        }
        [HttpGet]
        public IActionResult Index()
        {
            List<Personnel> personnels = new List<Personnel>();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Personnels/getall").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                personnels = JsonSerializer.Deserialize<List<Personnel>>(data, options);
            }
            return View(personnels);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Personnel personnel)
        {
            if (personnel == null) return View();
            try
            {                
                string data = JsonSerializer.Serialize<Personnel>(personnel, options);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Personnels/add", content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                return View();
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id == null || id == 0)
            {
                return RedirectToAction("Index");
            }
            try
            {
                Personnel personnel = new Personnel();
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Personnels/getbyid/" + id.ToString()).Result;
                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    personnel = JsonSerializer.Deserialize<Personnel>(data, options);
                }
                return View(personnel);                
            }
            catch (Exception ex)
            {
                return View();
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Personnel personnel)
        {
            if (personnel == null) return View();
            try
            {
                string data = JsonSerializer.Serialize<Personnel>(personnel, options);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Personnels/edit", content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                return View();
            }
            return View();
        }
    }
}

src/AssessmentEF.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/AssessmentEF.MVC/Views/Personnel/Add.cshtml
@model AssessmentEF.MVC.Models.Personnel

@{
    ViewData["Title"] = "Add";
}

<h1>Personel Ekle</h1>

<hr />
<div class="row">
    <div class="">
        <form asp-action="Add">
            <div class="form-row d-flex">
                <div class="form-group px-5 col-md-6">
                    <label asp-for="Name" class="sr-only"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group px-5 col-md-6">
                    <label asp-for="Surname" class="sr-only"></label>
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row d-flex">
                <div class="form-group px-5 col-md-6">
                    <label asp-for="BirthDate" class="control-label"></label>
                    <input asp-for="BirthDate" class="form-control" type="date" />
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>
                <div class="form-group px-5 col-md-6">
                    <label asp-for="Gender" class="control-label"></label>
                    <select asp-for="Gender" asp-items="@Html.GetEnumSelectList<Gender>()" class="form-control">
                        <option selected="selected" value="">Seçiminiz</option>
                    </select>
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row d-flex">
                <div class="form-group px-5 col-md-6">
                    <label asp-for="Salary.Department" class="control-label"></label>
                    <select asp-for="Salary.Department" asp-items="@Html.GetEnumSelectList<Department>()" class="form-control">
                        <option selected="selected" value="">Seçiminiz</option>
                    </select>
                </div>
                <div class="form-group px-5 col-md-6">
                    <label asp-for="Salary.PersonnelSalary" class="control-label"></label>
                    <input asp-for="Salary.PersonnelSalary" class="form-control" type="number" />
                </div>
            </div>
            <div class="form-group p-3 px-5 col-md-6">
                <input type="submit" value="   Ekle   " class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Geri Dön</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/AssessmentEF.MVC/Views/Personnel/Edit.cshtml
@model AssessmentEF.MVC.Models.Personnel

@{
    ViewData["Title"] = "Edit";
}

<h1>Personel Düzenle</h1>

<hr />
<div class="row">
    <div class="">
        <form asp-action="Edit">
            <input asp-for="ID" class="form-control" type="hidden" />
            <div class="form-row d-flex">
                <div class="form-group px-5 col-md-6">
                    <label asp-for="Name" class="sr-only"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group px-5 col-md-6">
                    <label asp-for="Surname" class="sr-only"></label>
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row d-flex">
                <div class="form-group px-5 col-md-6">
                    <label asp-for="BirthDate" class="control-label"></label>
                    <input asp-for="BirthDate" class="form-control" type="date" />
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>
                <div class="form-group px-5 col-md-6">
                    <label asp-for="Gender" class="control-label"></label>
                    <select asp-for="Gender" asp-items="@Html.GetEnumSelectList<Gender>()" class="form-control">
                        <option selected="selected" value="">Seçiminiz</option>
                    </select>
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row d-flex">
                <div class="form-group px-5 col-md-6">
                    <label asp-for="Salary.Department" class="control-label"></label>
                    <select asp-for="Salary.Department" asp-items="@Html.GetEnumSelectList<Department>()" class="form-control">
                        <option selected="selected" value="">Seçiminiz</option>
                    </select>
                </div>
                <div class="form-group px-5 col-md-6">
                    <label asp-for="Salary.PersonnelSalary" class="control-label"></label>
                    <input asp-for="Salary.PersonnelSalary" class="form-control" type="number" />
                </div>
            </div>
            <div class="form-group p-3 px-5 col-md-6">
                <input type="submit" value=" Güncelle " class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Geri Dön</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/AssessmentEF.MVC/Views/Personnel/Index.cshtml
@using AssessmentEF.MVC.Models;
@model List<Personnel>

@{
    ViewData["Title"] = "Index";
}

<h1>Personel Listesi</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                Adı
            </th>
            <th>
                Soyadı
            </th>
            <th>
                Doğum Tarihi
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.Surname
            </td>
            <td>
                    @item.BirthDate.ToString("dd/MM/yyyy")
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", "Personnel", new {  id=item.ID },new { @class= "btn btn-info"})
                
            </td>
        </tr>
}
    </tbody>
</table>

src/AssessmentEF.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OPTIIM Assessment EF MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AssessmentEF.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Personnel" asp-action="Index">OPTIIM Assessment EF MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personnel" asp-action="Index">Personel Listesi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personnel" asp-action="Add">Personel Ekle</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Fatih AKKAYA
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>